apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    kubernetes.io/name: "mosquitto"
spec:
  selector:
    app: mosquitto
  type: NodePort
  ports:
  - name: mqtt 
    port: 1883
    nodePort: 31883
  - name: mqtt-tls 
    port: 8883 
    nodePort: 31884
  - name: websockets
    port: 9001
    nodePort: 31885
  - name: websockets-tls
    port: 9002
    nodePort: 31886
  #externalIPs: ["10.0.1.19"]
