apiVersion: v1
kind: Endpoints
metadata:
  name: mosquitto
  namespace: default
subsets:
  - addresses:
    - ip: 10.1.0.32
    ports:
      - name: mqtt
        port: 31883
      - name: mqtt-tls 
        port: 31884
      - name: websockets
        port: 31885
      - name: websockets-tls
        port: 31886

